// Auto-generated by scripts/generate-province-maps.ts
// Source: statgarten/maps (MIT License)

export interface GuMapLocation {
  guId: string;
  name: string;
  path: string;
  labelX: number;
  labelY: number;
}

export const VIEWBOX = "0 0 800 944";
export const SIGUNGU_ID = "anyang";

export const GUS: GuMapLocation[] = [
  { guId: "dongan-gu", name: "동안구", path: "M 330.08 598.98 324.9 608.42 318.91 625.46 311.28 620.2 307.94 613.83 306.92 603.73 300.48 598.54 299.17 592.1 306.21 589.5 311.84 584.37 311.68 573.09 320.16 571.68 319.35 585.18 326.27 590.79 330.08 598.98 Z", labelX: 315, labelY: 597 },
  { guId: "manan-gu", name: "만안구", path: "M 311.68 573.09 311.84 584.37 306.21 589.5 299.17 592.1 300.48 598.54 306.92 603.73 307.94 613.83 295.32 614.91 288.74 625.35 283.27 626.7 280.23 615.85 275.18 614.44 272.05 602.21 272.91 597.79 272.49 591.84 279.49 591.38 283.59 582.06 285.03 572.88 290.65 576.21 300.95 565.74 307.36 575.05 311.68 573.09 Z", labelX: 293, labelY: 595 },
];
