// Auto-generated by scripts/generate-province-maps.ts

import type { SigunguMapLocation } from './seoul';

export type { SigunguMapLocation };

// Dynamic import helper for code-splitting
export async function loadProvinceMap(provinceId: string) {
  const mod = await import(`./${provinceId}`);
  return { viewBox: mod.VIEWBOX as string, sigungus: mod.SIGUNGUS as SigunguMapLocation[] };
}
